spring:
  data:
    mongodb:
      uri: mongodb://192.168.123.186:27017/admin
      #uri: mongodb://fooduser:foodpw@192.168.123.186:27017/test
#     uri: mongodb://<user>:<passwd>@<url>:<port>/<dbname>